package com.talkto.core.learn

import com.talkto.core.i18n.Lang

/** Lesson topics. [pictures] is false where the emoji do not tell the words apart (phrases, days). */
enum class Topic(val bg: String, val en: String, val emoji: String, val pictures: Boolean = true) {
    GREETINGS("Поздрави", "Greetings", "👋", pictures = false),
    ANIMALS("Животни", "Animals", "🐶"),
    COLORS("Цветове", "Colours", "🎨"),
    NUMBERS("Числа", "Numbers", "🔢"),
    FAMILY("Семейство", "Family", "👪"),
    FOOD("Храна", "Food", "🍕"),
    FRUIT("Плодове и зеленчуци", "Fruit and vegetables", "🍎"),
    BODY("Тяло", "Body", "👂"),
    CLOTHES("Дрехи", "Clothes", "👕"),
    HOME("Вкъщи", "At home", "🏠"),
    SCHOOL("Училище", "School", "🎒"),
    TOYS("Игри и играчки", "Toys and games", "🧸"),
    NATURE("Природа и време", "Nature and weather", "🌈"),
    TRANSPORT("Превозни средства", "Transport", "🚗"),
    ACTIONS("Действия", "Actions", "🏃"),
    FEELINGS("Чувства", "Feelings", "😄"),
    SEA("В морето", "In the sea", "🐳"),
    INSECTS("Буболечки", "Bugs and insects", "🐞"),
    JOBS("Професии", "Jobs", "🧑‍🚒"),
    SPORTS("Спорт", "Sports", "🏀"),
    SPACE("Космос", "Space", "🪐"),
    MUSIC("Музика", "Music", "🎹"),
    OPPOSITES("Какво е?", "Describing words", "⚖️"),
    DAYS("Дни и време", "Days and time", "📅", pictures = false);

    fun label(lang: Lang) = lang.pick(bg, en)
}

/**
 * A word or short phrase in both languages. [bgAlt] / [enAlt] are other accepted answers when the word is said
 * aloud: other genders ("щастлива"), synonyms ("pants"), digits the recogniser writes for numbers ("7").
 */
data class Word(
    val bg: String,
    val en: String,
    val emoji: String,
    val topic: Topic,
    val bgAlt: List<String> = emptyList(),
    val enAlt: List<String> = emptyList(),
) {
    val id: String get() = "${topic.name}:$en"

    fun text(lang: Lang) = lang.pick(bg, en)
    fun alternatives(lang: Lang) = if (lang == Lang.BG) bgAlt else enAlt
}

/** A question and its natural answer, for the "what would you say?" exercise. */
data class Exchange(val questionBg: String, val questionEn: String, val answerBg: String, val answerEn: String) {
    fun question(lang: Lang) = lang.pick(questionBg, questionEn)
    fun answer(lang: Lang) = lang.pick(answerBg, answerEn)
}

/**
 * The built-in word list: works offline, chosen for children and beginners, easy words first in each topic.
 * English is British where the two differ, with the American word accepted as an answer.
 */
object Vocabulary {
    private fun t(topic: Topic, vararg rows: Word) = rows.toList()
    private fun w(bg: String, en: String, emoji: String, topic: Topic, bgAlt: List<String> = emptyList(), enAlt: List<String> = emptyList()) =
        Word(bg, en, emoji, topic, bgAlt, enAlt)

    val words: List<Word> = listOf(
        t(
            Topic.GREETINGS,
            w("Здравей", "Hello", "👋", Topic.GREETINGS, listOf("здрасти", "здравейте"), listOf("hi", "hey")),
            w("Добро утро", "Good morning", "🌅", Topic.GREETINGS),
            w("Добър ден", "Good afternoon", "☀️", Topic.GREETINGS, enAlt = listOf("good day")),
            w("Добър вечер", "Good evening", "🌆", Topic.GREETINGS),
            w("Лека нощ", "Good night", "🌙", Topic.GREETINGS),
            w("Довиждане", "Goodbye", "🙋", Topic.GREETINGS, listOf("чао"), listOf("bye")),
            w("Благодаря", "Thank you", "🙏", Topic.GREETINGS, listOf("мерси"), listOf("thanks")),
            w("Моля", "Please", "🥺", Topic.GREETINGS),
            w("Извинявай", "Sorry", "😔", Topic.GREETINGS, listOf("извинете", "съжалявам")),
            w("Да", "Yes", "👍", Topic.GREETINGS),
            w("Не", "No", "👎", Topic.GREETINGS),
            w("Как си?", "How are you?", "🙂", Topic.GREETINGS),
            w("Добре съм", "I'm fine", "😊", Topic.GREETINGS, enAlt = listOf("i am fine", "fine")),
            w("Казвам се…", "My name is…", "📛", Topic.GREETINGS),
            w("Приятно ми е", "Nice to meet you", "🤝", Topic.GREETINGS),
        ),
        t(
            Topic.ANIMALS,
            w("куче", "dog", "🐶", Topic.ANIMALS, enAlt = listOf("doggy", "puppy")),
            w("котка", "cat", "🐱", Topic.ANIMALS, listOf("коте"), listOf("kitty", "kitten")),
            w("риба", "fish", "🐟", Topic.ANIMALS),
            w("птица", "bird", "🐦", Topic.ANIMALS, listOf("птиче")),
            w("кон", "horse", "🐴", Topic.ANIMALS),
            w("крава", "cow", "🐮", Topic.ANIMALS),
            w("прасе", "pig", "🐷", Topic.ANIMALS),
            w("овца", "sheep", "🐑", Topic.ANIMALS),
            w("кокошка", "chicken", "🐔", Topic.ANIMALS, enAlt = listOf("hen")),
            w("патица", "duck", "🦆", Topic.ANIMALS),
            w("мишка", "mouse", "🐭", Topic.ANIMALS),
            w("заек", "rabbit", "🐰", Topic.ANIMALS, listOf("зайче"), listOf("bunny")),
            w("жаба", "frog", "🐸", Topic.ANIMALS),
            w("мечка", "bear", "🐻", Topic.ANIMALS),
            w("лъв", "lion", "🦁", Topic.ANIMALS),
            w("тигър", "tiger", "🐯", Topic.ANIMALS),
            w("слон", "elephant", "🐘", Topic.ANIMALS),
            w("маймуна", "monkey", "🐵", Topic.ANIMALS),
            w("жираф", "giraffe", "🦒", Topic.ANIMALS),
            w("пеперуда", "butterfly", "🦋", Topic.ANIMALS),
            w("змия", "snake", "🐍", Topic.ANIMALS),
            w("костенурка", "turtle", "🐢", Topic.ANIMALS, enAlt = listOf("tortoise")),
            w("пингвин", "penguin", "🐧", Topic.ANIMALS),
            w("лисица", "fox", "🦊", Topic.ANIMALS),
            w("вълк", "wolf", "🐺", Topic.ANIMALS),
        ),
        t(
            Topic.COLORS,
            w("червен", "red", "🔴", Topic.COLORS, listOf("червена", "червено")),
            w("син", "blue", "🔵", Topic.COLORS, listOf("синя", "синьо")),
            w("зелен", "green", "🟢", Topic.COLORS, listOf("зелена", "зелено")),
            w("жълт", "yellow", "🟡", Topic.COLORS, listOf("жълта", "жълто")),
            w("оранжев", "orange", "🟠", Topic.COLORS, listOf("оранжева", "оранжево")),
            w("лилав", "purple", "🟣", Topic.COLORS, listOf("лилава", "лилаво", "виолетов")),
            w("розов", "pink", "💗", Topic.COLORS, listOf("розова", "розово")),
            w("черен", "black", "⚫", Topic.COLORS, listOf("черна", "черно")),
            w("бял", "white", "⚪", Topic.COLORS, listOf("бяла", "бяло")),
            w("кафяв", "brown", "🟤", Topic.COLORS, listOf("кафява", "кафяво")),
        ),
        t(
            Topic.NUMBERS,
            w("едно", "one", "1️⃣", Topic.NUMBERS, listOf("1", "един", "една"), listOf("1")),
            w("две", "two", "2️⃣", Topic.NUMBERS, listOf("2", "два"), listOf("2")),
            w("три", "three", "3️⃣", Topic.NUMBERS, listOf("3"), listOf("3")),
            w("четири", "four", "4️⃣", Topic.NUMBERS, listOf("4"), listOf("4")),
            w("пет", "five", "5️⃣", Topic.NUMBERS, listOf("5"), listOf("5")),
            w("шест", "six", "6️⃣", Topic.NUMBERS, listOf("6"), listOf("6")),
            w("седем", "seven", "7️⃣", Topic.NUMBERS, listOf("7"), listOf("7")),
            w("осем", "eight", "8️⃣", Topic.NUMBERS, listOf("8"), listOf("8")),
            w("девет", "nine", "9️⃣", Topic.NUMBERS, listOf("9"), listOf("9")),
            w("десет", "ten", "🔟", Topic.NUMBERS, listOf("10"), listOf("10")),
            w("нула", "zero", "0️⃣", Topic.NUMBERS, listOf("0"), listOf("0")),
            w("сто", "one hundred", "💯", Topic.NUMBERS, listOf("100"), listOf("100", "hundred", "a hundred")),
        ),
        t(
            Topic.FAMILY,
            w("мама", "mum", "👩", Topic.FAMILY, listOf("майка"), listOf("mom", "mother", "mummy", "mommy")),
            w("татко", "dad", "👨", Topic.FAMILY, listOf("баща", "тате"), listOf("father", "daddy")),
            w("брат", "brother", "👦", Topic.FAMILY, listOf("братче")),
            w("сестра", "sister", "👧", Topic.FAMILY, listOf("сестричка")),
            w("баба", "grandma", "👵", Topic.FAMILY, enAlt = listOf("grandmother", "granny")),
            w("дядо", "grandpa", "👴", Topic.FAMILY, enAlt = listOf("grandfather", "granddad")),
            w("бебе", "baby", "👶", Topic.FAMILY),
            w("семейство", "family", "👪", Topic.FAMILY),
            w("приятел", "friend", "🧑‍🤝‍🧑", Topic.FAMILY, listOf("приятелка")),
            w("чичо", "uncle", "🧔", Topic.FAMILY, listOf("вуйчо")),
            w("леля", "aunt", "👩‍🦰", Topic.FAMILY, listOf("стринка", "вуйна"), listOf("auntie")),
        ),
        t(
            Topic.FOOD,
            w("хляб", "bread", "🍞", Topic.FOOD),
            w("мляко", "milk", "🥛", Topic.FOOD),
            w("вода", "water", "💧", Topic.FOOD),
            w("сирене", "cheese", "🧀", Topic.FOOD),
            w("яйце", "egg", "🥚", Topic.FOOD),
            w("пица", "pizza", "🍕", Topic.FOOD),
            w("торта", "cake", "🎂", Topic.FOOD),
            w("сладолед", "ice cream", "🍦", Topic.FOOD),
            w("шоколад", "chocolate", "🍫", Topic.FOOD),
            w("бонбон", "sweet", "🍬", Topic.FOOD, enAlt = listOf("candy", "sweets")),
            w("сок", "juice", "🧃", Topic.FOOD),
            w("чай", "tea", "🍵", Topic.FOOD),
            w("супа", "soup", "🍲", Topic.FOOD),
            w("месо", "meat", "🥩", Topic.FOOD),
            w("ориз", "rice", "🍚", Topic.FOOD),
            w("мед", "honey", "🍯", Topic.FOOD),
        ),
        t(
            Topic.FRUIT,
            w("ябълка", "apple", "🍎", Topic.FRUIT),
            w("банан", "banana", "🍌", Topic.FRUIT),
            w("портокал", "orange", "🍊", Topic.FRUIT),
            w("ягода", "strawberry", "🍓", Topic.FRUIT),
            w("грозде", "grapes", "🍇", Topic.FRUIT, enAlt = listOf("grape")),
            w("круша", "pear", "🍐", Topic.FRUIT),
            w("лимон", "lemon", "🍋", Topic.FRUIT),
            w("диня", "watermelon", "🍉", Topic.FRUIT),
            w("череша", "cherry", "🍒", Topic.FRUIT, listOf("черешка"), listOf("cherries")),
            w("морков", "carrot", "🥕", Topic.FRUIT),
            w("домат", "tomato", "🍅", Topic.FRUIT),
            w("картоф", "potato", "🥔", Topic.FRUIT),
            w("краставица", "cucumber", "🥒", Topic.FRUIT),
            w("царевица", "corn", "🌽", Topic.FRUIT, enAlt = listOf("sweetcorn", "maize")),
        ),
        t(
            Topic.BODY,
            w("око", "eye", "👁️", Topic.BODY, listOf("очи"), listOf("eyes")),
            w("ухо", "ear", "👂", Topic.BODY, listOf("уши"), listOf("ears")),
            w("нос", "nose", "👃", Topic.BODY, listOf("носле")),
            w("уста", "mouth", "👄", Topic.BODY),
            w("зъб", "tooth", "🦷", Topic.BODY, listOf("зъби"), listOf("teeth")),
            w("ръка", "hand", "✋", Topic.BODY, listOf("ръце"), listOf("hands", "arm")),
            w("крак", "leg", "🦵", Topic.BODY, listOf("крака"), listOf("legs", "foot")),
            w("коса", "hair", "💇", Topic.BODY),
            w("лице", "face", "🙂", Topic.BODY),
            w("сърце", "heart", "❤️", Topic.BODY),
            w("език", "tongue", "👅", Topic.BODY),
        ),
        t(
            Topic.CLOTHES,
            w("тениска", "T-shirt", "👕", Topic.CLOTHES, listOf("блуза"), listOf("tshirt", "t shirt", "shirt")),
            w("панталон", "trousers", "👖", Topic.CLOTHES, listOf("панталони", "дънки"), listOf("pants", "jeans")),
            w("рокля", "dress", "👗", Topic.CLOTHES),
            w("обувки", "shoes", "👟", Topic.CLOTHES, listOf("обувка", "маратонки"), listOf("shoe", "trainers", "sneakers")),
            w("шапка", "hat", "🧢", Topic.CLOTHES, enAlt = listOf("cap")),
            w("чорапи", "socks", "🧦", Topic.CLOTHES, listOf("чорап"), listOf("sock")),
            w("шал", "scarf", "🧣", Topic.CLOTHES),
            w("ръкавици", "gloves", "🧤", Topic.CLOTHES, listOf("ръкавица"), listOf("glove")),
            w("яке", "jacket", "🧥", Topic.CLOTHES, listOf("палто"), listOf("coat")),
            w("очила", "glasses", "👓", Topic.CLOTHES),
            w("чанта", "bag", "👜", Topic.CLOTHES),
        ),
        t(
            Topic.HOME,
            w("къща", "house", "🏠", Topic.HOME, listOf("вкъщи", "дом"), listOf("home")),
            w("врата", "door", "🚪", Topic.HOME),
            w("прозорец", "window", "🪟", Topic.HOME),
            w("легло", "bed", "🛏️", Topic.HOME),
            w("стол", "chair", "🪑", Topic.HOME),
            w("лампа", "lamp", "💡", Topic.HOME, listOf("крушка"), listOf("light", "light bulb")),
            w("телевизор", "television", "📺", Topic.HOME, enAlt = listOf("tv", "telly")),
            w("телефон", "phone", "📱", Topic.HOME, enAlt = listOf("telephone", "mobile")),
            w("часовник", "clock", "⏰", Topic.HOME, enAlt = listOf("watch")),
            w("ключ", "key", "🔑", Topic.HOME),
            w("вана", "bath", "🛁", Topic.HOME, enAlt = listOf("bathtub")),
            w("огледало", "mirror", "🪞", Topic.HOME),
        ),
        t(
            Topic.SCHOOL,
            w("училище", "school", "🏫", Topic.SCHOOL),
            w("книга", "book", "📖", Topic.SCHOOL, listOf("книжка")),
            w("молив", "pencil", "✏️", Topic.SCHOOL),
            w("химикалка", "pen", "🖊️", Topic.SCHOOL, listOf("химикал")),
            w("тетрадка", "notebook", "📓", Topic.SCHOOL, listOf("тетрадки"), listOf("exercise book")),
            w("раница", "school bag", "🎒", Topic.SCHOOL, listOf("чанта"), listOf("backpack", "rucksack", "schoolbag")),
            w("учител", "teacher", "🧑‍🏫", Topic.SCHOOL, listOf("учителка", "учителката")),
            w("ножица", "scissors", "✂️", Topic.SCHOOL, listOf("ножички")),
            w("линийка", "ruler", "📏", Topic.SCHOOL),
            w("компютър", "computer", "💻", Topic.SCHOOL, enAlt = listOf("laptop")),
            w("картина", "picture", "🖼️", Topic.SCHOOL, listOf("рисунка"), listOf("painting")),
        ),
        t(
            Topic.TOYS,
            w("топка", "ball", "⚽", Topic.TOYS),
            w("мече", "teddy bear", "🧸", Topic.TOYS, enAlt = listOf("teddy")),
            w("кукла", "doll", "🪆", Topic.TOYS),
            w("балон", "balloon", "🎈", Topic.TOYS),
            w("хвърчило", "kite", "🪁", Topic.TOYS),
            w("пъзел", "puzzle", "🧩", Topic.TOYS, listOf("пъзели"), listOf("jigsaw")),
            w("игра", "game", "🎮", Topic.TOYS),
            w("барабан", "drum", "🥁", Topic.TOYS),
            w("китара", "guitar", "🎸", Topic.TOYS),
            w("подарък", "present", "🎁", Topic.TOYS, listOf("подаръци"), listOf("gift")),
        ),
        t(
            Topic.NATURE,
            w("слънце", "sun", "☀️", Topic.NATURE, listOf("слънчево")),
            w("луна", "moon", "🌙", Topic.NATURE),
            w("звезда", "star", "⭐", Topic.NATURE, listOf("звездичка", "звезди"), listOf("stars")),
            w("облак", "cloud", "☁️", Topic.NATURE, listOf("облаци", "облачно"), listOf("clouds", "cloudy")),
            w("дъжд", "rain", "🌧️", Topic.NATURE, listOf("вали"), listOf("rainy", "raining")),
            w("сняг", "snow", "❄️", Topic.NATURE, enAlt = listOf("snowy", "snowing")),
            w("вятър", "wind", "🌬️", Topic.NATURE, listOf("ветровито"), listOf("windy")),
            w("дъга", "rainbow", "🌈", Topic.NATURE),
            w("дърво", "tree", "🌳", Topic.NATURE, listOf("дървета"), listOf("trees")),
            w("цвете", "flower", "🌸", Topic.NATURE, listOf("цветя", "цветенце"), listOf("flowers")),
            w("гора", "forest", "🌲", Topic.NATURE, enAlt = listOf("woods", "wood")),
            w("море", "sea", "🌊", Topic.NATURE),
            w("планина", "mountain", "⛰️", Topic.NATURE),
            w("огън", "fire", "🔥", Topic.NATURE),
        ),
        t(
            Topic.TRANSPORT,
            w("кола", "car", "🚗", Topic.TRANSPORT, listOf("автомобил")),
            w("автобус", "bus", "🚌", Topic.TRANSPORT),
            w("влак", "train", "🚆", Topic.TRANSPORT, listOf("влакче")),
            w("самолет", "plane", "✈️", Topic.TRANSPORT, enAlt = listOf("aeroplane", "airplane")),
            w("кораб", "ship", "🚢", Topic.TRANSPORT),
            w("лодка", "boat", "⛵", Topic.TRANSPORT),
            w("колело", "bike", "🚲", Topic.TRANSPORT, listOf("велосипед"), listOf("bicycle")),
            w("мотор", "motorbike", "🏍️", Topic.TRANSPORT, listOf("мотоциклет"), listOf("motorcycle")),
            w("камион", "lorry", "🚚", Topic.TRANSPORT, enAlt = listOf("truck")),
            w("ракета", "rocket", "🚀", Topic.TRANSPORT),
            w("хеликоптер", "helicopter", "🚁", Topic.TRANSPORT),
            w("такси", "taxi", "🚕", Topic.TRANSPORT, enAlt = listOf("cab")),
        ),
        t(
            Topic.ACTIONS,
            w("ям", "eat", "🍽️", Topic.ACTIONS, listOf("яде", "яж", "ядем")),
            w("пия", "drink", "🥤", Topic.ACTIONS, listOf("пие", "пий")),
            w("спя", "sleep", "😴", Topic.ACTIONS, listOf("спи", "спим")),
            w("тичам", "run", "🏃", Topic.ACTIONS, listOf("тича", "бягам", "тичай")),
            w("скачам", "jump", "🦘", Topic.ACTIONS, listOf("скача", "скачай")),
            w("плувам", "swim", "🏊", Topic.ACTIONS, listOf("плува", "плувай")),
            w("пея", "sing", "🎤", Topic.ACTIONS, listOf("пее", "пей")),
            w("танцувам", "dance", "💃", Topic.ACTIONS, listOf("танцува", "танцувай")),
            w("чета", "read", "📚", Topic.ACTIONS, listOf("чете", "чети")),
            w("пиша", "write", "✍️", Topic.ACTIONS, listOf("пише", "пиши")),
            w("рисувам", "draw", "🎨", Topic.ACTIONS, listOf("рисува", "рисувай"), listOf("paint")),
            w("играя", "play", "🎲", Topic.ACTIONS, listOf("играе", "играй", "играем")),
            w("смея се", "laugh", "😂", Topic.ACTIONS, listOf("смее се", "смей се")),
            w("плача", "cry", "😭", Topic.ACTIONS, listOf("плаче", "плачи")),
        ),
        t(
            Topic.FEELINGS,
            w("щастлив", "happy", "😄", Topic.FEELINGS, listOf("щастлива", "весел", "весела")),
            w("тъжен", "sad", "😢", Topic.FEELINGS, listOf("тъжна", "тъжно")),
            w("ядосан", "angry", "😠", Topic.FEELINGS, listOf("ядосана", "сърдит", "сърдита"), listOf("cross", "mad")),
            w("уплашен", "scared", "😨", Topic.FEELINGS, listOf("уплашена", "страх ме е"), listOf("afraid", "frightened")),
            w("изморен", "tired", "🥱", Topic.FEELINGS, listOf("изморена", "уморен", "уморена"), listOf("sleepy")),
            w("гладен", "hungry", "🤤", Topic.FEELINGS, listOf("гладна")),
            w("болен", "ill", "🤒", Topic.FEELINGS, listOf("болна"), listOf("sick")),
            w("изненадан", "surprised", "😲", Topic.FEELINGS, listOf("изненадана")),
            w("спокоен", "calm", "😌", Topic.FEELINGS, listOf("спокойна")),
        ),
        t(
            Topic.SEA,
            w("кит", "whale", "🐳", Topic.SEA),
            w("делфин", "dolphin", "🐬", Topic.SEA),
            w("акула", "shark", "🦈", Topic.SEA),
            w("октопод", "octopus", "🐙", Topic.SEA, listOf("октопод", "сепия")),
            w("рак", "crab", "🦀", Topic.SEA, listOf("раче")),
            w("мида", "shell", "🐚", Topic.SEA, listOf("раковина", "миди"), listOf("seashell")),
            w("тюлен", "seal", "🦭", Topic.SEA),
            w("скарида", "shrimp", "🦐", Topic.SEA, listOf("скариди"), listOf("prawn")),
            w("калмар", "squid", "🦑", Topic.SEA),
            w("рибка", "tropical fish", "🐠", Topic.SEA, listOf("тропическа рибка"), listOf("fish")),
            w("риба балон", "pufferfish", "🐡", Topic.SEA, listOf("риба-балон"), listOf("puffer fish", "blowfish")),
        ),
        t(
            Topic.INSECTS,
            w("пчела", "bee", "🐝", Topic.INSECTS, listOf("пчеличка")),
            w("калинка", "ladybird", "🐞", Topic.INSECTS, enAlt = listOf("ladybug")),
            w("мравка", "ant", "🐜", Topic.INSECTS, listOf("мравчица")),
            w("щурец", "cricket", "🦗", Topic.INSECTS, listOf("скакалец"), listOf("grasshopper")),
            w("паяк", "spider", "🕷️", Topic.INSECTS, listOf("паяче")),
            w("охлюв", "snail", "🐌", Topic.INSECTS),
            w("бръмбар", "beetle", "🪲", Topic.INSECTS),
            w("гъсеница", "caterpillar", "🐛", Topic.INSECTS),
            w("комар", "mosquito", "🦟", Topic.INSECTS),
            w("муха", "fly", "🪰", Topic.INSECTS, listOf("мушица")),
            w("скорпион", "scorpion", "🦂", Topic.INSECTS),
        ),
        t(
            Topic.JOBS,
            w("лекар", "doctor", "🧑‍⚕️", Topic.JOBS, listOf("доктор", "лекарка", "докторка")),
            w("пожарникар", "firefighter", "🧑‍🚒", Topic.JOBS, enAlt = listOf("fireman")),
            w("полицай", "police officer", "👮", Topic.JOBS, listOf("полицайка", "полицията"), listOf("policeman", "policewoman")),
            w("готвач", "cook", "🧑‍🍳", Topic.JOBS, listOf("готвачка"), listOf("chef")),
            w("фермер", "farmer", "🧑‍🌾", Topic.JOBS, listOf("фермерка", "селянин")),
            w("космонавт", "astronaut", "🧑‍🚀", Topic.JOBS, listOf("астронавт")),
            w("художник", "artist", "🧑‍🎨", Topic.JOBS, listOf("художничка"), listOf("painter")),
            w("пилот", "pilot", "🧑‍✈️", Topic.JOBS),
            w("певец", "singer", "🧑‍🎤", Topic.JOBS, listOf("певица")),
            w("програмист", "programmer", "🧑‍💻", Topic.JOBS, listOf("програмистка"), listOf("coder")),
            w("строител", "builder", "👷", Topic.JOBS),
            w("механик", "mechanic", "🧑‍🔧", Topic.JOBS),
        ),
        t(
            Topic.SPORTS,
            w("футбол", "football", "⚽", Topic.SPORTS, enAlt = listOf("soccer")),
            w("баскетбол", "basketball", "🏀", Topic.SPORTS),
            w("тенис", "tennis", "🎾", Topic.SPORTS),
            w("волейбол", "volleyball", "🏐", Topic.SPORTS),
            w("плуване", "swimming", "🏊", Topic.SPORTS),
            w("ски", "skiing", "⛷️", Topic.SPORTS, enAlt = listOf("ski")),
            w("колоездене", "cycling", "🚴", Topic.SPORTS),
            w("бокс", "boxing", "🥊", Topic.SPORTS),
            w("гимнастика", "gymnastics", "🤸", Topic.SPORTS),
            w("хокей", "hockey", "🏒", Topic.SPORTS),
            w("шах", "chess", "♟️", Topic.SPORTS),
            w("бягане", "running", "🏃", Topic.SPORTS),
        ),
        t(
            Topic.SPACE,
            w("планета", "planet", "🪐", Topic.SPACE, listOf("планети"), listOf("planets")),
            w("Земя", "Earth", "🌍", Topic.SPACE, listOf("земята", "земното кълбо"), listOf("the earth", "world")),
            w("звезда", "star", "⭐", Topic.SPACE, listOf("звезди"), listOf("stars")),
            w("луна", "moon", "🌙", Topic.SPACE, listOf("луната")),
            w("слънце", "sun", "☀️", Topic.SPACE, listOf("слънцето")),
            w("ракета", "rocket", "🚀", Topic.SPACE),
            w("комета", "comet", "☄️", Topic.SPACE),
            w("телескоп", "telescope", "🔭", Topic.SPACE),
            w("спътник", "satellite", "🛰️", Topic.SPACE),
            w("извънземно", "alien", "👽", Topic.SPACE, listOf("извънземен", "извънземни")),
            w("летяща чиния", "flying saucer", "🛸", Topic.SPACE, enAlt = listOf("ufo")),
        ),
        t(
            Topic.MUSIC,
            w("пиано", "piano", "🎹", Topic.MUSIC),
            w("цигулка", "violin", "🎻", Topic.MUSIC),
            w("тромпет", "trumpet", "🎺", Topic.MUSIC, listOf("тръба")),
            w("саксофон", "saxophone", "🎷", Topic.MUSIC, enAlt = listOf("sax")),
            w("китара", "guitar", "🎸", Topic.MUSIC),
            w("барабан", "drum", "🥁", Topic.MUSIC, listOf("барабани"), listOf("drums")),
            w("песен", "song", "🎵", Topic.MUSIC, listOf("песничка")),
            w("микрофон", "microphone", "🎤", Topic.MUSIC, enAlt = listOf("mic")),
            w("слушалки", "headphones", "🎧", Topic.MUSIC),
            w("акордеон", "accordion", "🪗", Topic.MUSIC),
            w("звънче", "bell", "🔔", Topic.MUSIC, listOf("камбанка", "камбана")),
        ),
        t(
            Topic.OPPOSITES,
            w("голям", "big", "🐘", Topic.OPPOSITES, listOf("голяма", "голямо"), listOf("large")),
            w("малък", "small", "🐜", Topic.OPPOSITES, listOf("малка", "малко"), listOf("little")),
            w("горещ", "hot", "🔥", Topic.OPPOSITES, listOf("гореща", "горещо", "топъл")),
            w("студен", "cold", "🧊", Topic.OPPOSITES, listOf("студена", "студено")),
            w("бърз", "fast", "🐆", Topic.OPPOSITES, listOf("бърза", "бързо"), listOf("quick")),
            w("бавен", "slow", "🐢", Topic.OPPOSITES, listOf("бавна", "бавно")),
            w("висок", "tall", "🦒", Topic.OPPOSITES, listOf("висока", "високо"), listOf("high")),
            w("стар", "old", "👴", Topic.OPPOSITES, listOf("стара", "старо")),
            w("млад", "young", "👶", Topic.OPPOSITES, listOf("млада", "младо")),
            w("мокър", "wet", "💦", Topic.OPPOSITES, listOf("мокра", "мокро")),
            w("силен", "strong", "💪", Topic.OPPOSITES, listOf("силна", "силно")),
            w("лек", "light", "🪶", Topic.OPPOSITES, listOf("лека", "леко")),
            w("тежък", "heavy", "🏋️", Topic.OPPOSITES, listOf("тежка", "тежко")),
            w("красив", "beautiful", "🌺", Topic.OPPOSITES, listOf("красива", "красиво", "хубав", "хубава"), listOf("pretty", "lovely")),
        ),
        t(
            Topic.DAYS,
            w("понеделник", "Monday", "📅", Topic.DAYS),
            w("вторник", "Tuesday", "📅", Topic.DAYS),
            w("сряда", "Wednesday", "📅", Topic.DAYS),
            w("четвъртък", "Thursday", "📅", Topic.DAYS),
            w("петък", "Friday", "📅", Topic.DAYS),
            w("събота", "Saturday", "📅", Topic.DAYS),
            w("неделя", "Sunday", "📅", Topic.DAYS),
            w("днес", "today", "📅", Topic.DAYS),
            w("утре", "tomorrow", "📅", Topic.DAYS),
            w("вчера", "yesterday", "📅", Topic.DAYS),
        ),
    ).flatten()

    fun of(topic: Topic): List<Word> = words.filter { it.topic == topic }

    val exchanges: List<Exchange> = listOf(
        Exchange("Как си?", "How are you?", "Добре съм, благодаря.", "I'm fine, thank you."),
        Exchange("Как се казваш?", "What's your name?", "Казвам се Ана.", "My name is Anna."),
        Exchange("На колко години си?", "How old are you?", "На седем години съм.", "I'm seven years old."),
        Exchange("Откъде си?", "Where are you from?", "От България съм.", "I'm from Bulgaria."),
        Exchange("Какъв е любимият ти цвят?", "What's your favourite colour?", "Любимият ми цвят е синият.", "My favourite colour is blue."),
        Exchange("Искаш ли да играем?", "Do you want to play?", "Да, искам!", "Yes, I do!"),
        Exchange("Гладен ли си?", "Are you hungry?", "Да, искам една ябълка.", "Yes, I'd like an apple."),
        Exchange("Колко е часът?", "What time is it?", "Три часът е.", "It's three o'clock."),
        Exchange("Какво е времето днес?", "What's the weather like today?", "Слънчево е.", "It's sunny."),
        Exchange("Имаш ли домашен любимец?", "Do you have a pet?", "Да, имам куче.", "Yes, I have a dog."),
        Exchange("Благодаря!", "Thank you!", "Моля!", "You're welcome!"),
        Exchange("Лека нощ!", "Good night!", "Лека нощ, сладки сънища!", "Good night, sweet dreams!"),
        Exchange("Какво обичаш да ядеш?", "What do you like to eat?", "Обичам пица.", "I like pizza."),
        Exchange("Къде е котката?", "Where is the cat?", "Котката е под масата.", "The cat is under the table."),
    )
}
